[tool.pulp_cli_template]
app_label = "maven"
glue = true
docs = false
translations = false
test_matrix = """
- python: "3.11"
  image_tag: "nightly"
  pulp_api_root: "/relocated/djnd/"
- python: "3.8"
  image_tag: "3.27"
- python: "3.12"
  image_tag: "3.23"
  lower_bounds: true
- python: "3.8"
  image_tag: "3.22"
- python: "3.9"
  image_tag: "3.21"
  pulp_api_root: "/relocated/djnd/"
- python: "3.10"
  image_tag: "3.18"
  lower_bounds: true
"""

[tool.towncrier]
package = "pulpcore.cli.maven"
filename = "CHANGES.md"
directory = "CHANGES/"
title_format = "## {version} ({project_date})"
template = "CHANGES/.TEMPLATE.md"
issue_format = "[#{issue}](https://github.com/pulp/pulp-cli-maven/issues/{issue})"
start_string = "[//]: # (towncrier release notes start)\n"

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "translation"
name = "Translations"
showcontent = true

[[tool.towncrier.type]]
directory = "devel"
name = "Developer Notes"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = false

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
markers = [
  "script: tests provided as shell scripts",
  "help_page: tests that render help pages",
  "pulp_ostree: pulp_ostree tests",
]

[tool.mypy]
strict = true
show_error_codes = true
files = "pulpcore/**/*.py"
namespace_packages = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
  "click_shell.*",
  "schema.*",
]
ignore_missing_imports = true
